/** User-facing API error messages (Japanese). */
export const API_ERRORS = {
  unauthorized: "ログインが必要です",
  forbidden: "この操作を行う権限がありません",
  notFound: "データが見つかりません",
  invalidJson: "リクエストの形式が正しくありません",
  invalidRequest: "リクエストが正しくありません",
  jobNotFound: "求人が見つかりません",
  applicationNotFound: "応募が見つかりません",
  accountNotFound: "アカウントが見つかりません",
  jobIdRequired: "求人IDが必要です",
  applicationIdRequired: "応募IDが必要です",
  idAndStatusRequired: "IDとステータスが必要です",
  idRequired: "IDが必要です",
  idAndApprovalStatusRequired: "IDと承認ステータスが必要です",
  applicationIdAndContentRequired: "応募IDとメッセージ内容が必要です",
  companyIdOrCompanyRequired: "企業IDまたは企業名が必要です",
  invalidDaysParameter: "日数の指定が正しくありません",
  invalidBirthday: "生年月日が正しくありません",
  invalidKind: "アップロード種別が正しくありません",
  fileRequired: "ファイルを選択してください",
  kindRequired: "アップロード種別を指定してください",
  statusActiveOrSuspended: "ステータスはActiveまたはSuspendedを指定してください",
  adminOnlyApproval: "承認ステータスの変更は管理者のみ可能です",
  signupFirst: "先にアカウント登録を行ってください",
  companyRegisterFieldsRequired:
    "メールアドレス、パスワード、企業名、担当者名を入力してください",
  wrongRole: "このアカウントではログインできません",
  jwtNotConfigured: "認証の設定が完了していません。管理者にお問い合わせください",
  profileSaveFailed: "プロフィールの保存に失敗しました",
  userCreationFailed: "ユーザー作成に失敗しました",
  r2NotConfigured: "ファイルストレージの設定が完了していません",
  loginFieldsRequired: "メールアドレスとパスワードを入力してください",
  invalidCredentials: "メールアドレスまたはパスワードが正しくありません",
  accountSuspended: "アカウントが停止されています",
  profileNotFound: "プロフィールが見つかりません。登録を完了してください。",
  seekerProfileNotFound: "プロフィールが見つかりません",
  authUserIdRequired: "認証情報が必要です",
  noFieldsToUpdate: "更新する項目がありません",
  jobNotAvailable: "この求人は現在利用できません",
  linkedCompanyNotFound: "紐づく企業が見つかりません",
  companyNotFound: "企業が見つかりません",
  companyRequired: "企業名を入力してください",
} as const;

export type ApiErrorKey = keyof typeof API_ERRORS;
